### PR TITLE
#3 Enhancement of Landing page

### PR DESCRIPTION
**Pull request by Khushi-Gupta13**
#3 Enhancement of landing page - I have added certain new looks to the website for getting an attractive look.

### CODE REVIEW

**Comment by Khushi-Gupta13** [comment]
Had a great experience working on this project. Thank you for assigning the
task.

**Comment by Khushi-Gupta13** [comment]
hi @Moses-main can you add hacktober label to the repository as it isn't counted as my contribution to hacktober fest

**Comment by Moses-main** [comment]
Ok @Khushi-Gupta13

**Comment by Khushi-Gupta13** [comment]
Thank you

**Comment by Khushi-Gupta13** [comment]
Sorry for distrubing again but you need to add hacktober accpted label as well.

**Comment by Khushi-Gupta13** [comment]
Please add the hacktober accepted label as well and include this within hacktober topic. I'll be highly obliged for this act of kindness.

**Comment by Khushi-Gupta13** [comment]
Please add the hacktober accepted label as well and include this within
hacktober topic. I'll be highly obliged for this act of kindness.

**Comment by Khushi-Gupta13** [comment]
Hi @Moses-main can you please do the needful.

**Comment by Moses-main** [comment]
Done @Khushi-Gupta13

**Comment by Khushi-Gupta13** [comment]
Thanks a lot.

**Pull request merged**
